openapi: 3.0.0
info:
  title: ex2-LO API
  version: 1.0.0
  description: API for optimizing integer linear programming problems.
servers:
  - url: http://localhost:5000
paths:
  /api/optimize:
    post:
      summary: Optimize variables with a budget constraint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                variables:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      lowerBound:
                        type: integer
                      upperBound:
                        type: integer
                        nullable: true
                      profit:
                        type: number
                      integer:
                        type: boolean
                      multiplier:
                        type: number
                budget:
                  type: integer
              required:
                - variables
                - budget
            example:
              variables:
                - name: coffee cake
                  lowerBound: 0
                  upperBound: null
                  profit: 1.8
                  integer: true
                  multiplier: 8
              budget: 100
      responses:
        '200':
          description: Optimization result
          content:
            application/json:
              schema:
                type: object
                properties:
                  max_profit:
                    type: number
                  result:
                    type: object
                    additionalProperties:
                      type: number
              example:
                max_profit: 42.5
                result:
                  coffee cake: 8
                  chocolate cake: 12
        '400':
          description: Invalid input
        '500':
          description: Server error
